version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pitza_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pitza_test
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pitza_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pitza_test
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    # Удаляем или комментируем следующую строку, если она была:
    # command: ["./pitza-backend"]
    # Оставляем запуск по умолчанию из Dockerfile.dev:
    # CMD diesel migration run && cargo run

volumes:
  pgdata: