FROM rust:1.82

WORKDIR /app

# Установим diesel_cli для миграций
RUN cargo install diesel_cli --no-default-features --features postgres

# Копируем только Cargo.toml и Cargo.lock для кэширования зависимостей
COPY Cargo.toml .
COPY Cargo.lock .
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo fetch

# Копируем исходники (остальное)
COPY . .

# Открываем порт
EXPOSE 8080

# Применяем миграции и запускаем сервер (debug)
CMD diesel migration run && cargo run