version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: gogarid/pitza-backend:latest
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata: