name: CI/CD Backend

on:
  push:
    branches: [main]
    paths:
      - '**.rs'
      - 'Cargo.*'
      - 'src/**'
      - 'migrations/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Кэш cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Сборка проекта
        run: cargo build --all

      - name: Установка diesel_cli
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Установка cargo-audit
        run: cargo install cargo-audit

      - name: Сохранение артефактов target
        uses: actions/upload-artifact@v4
        with:
          name: target-artifact
          path: target

      - name: Сохранение diesel_cli
        uses: actions/upload-artifact@v4
        with:
          name: diesel-cli
          path: ~/.cargo/bin/diesel

      - name: Сохранение cargo-audit
        uses: actions/upload-artifact@v4
        with:
          name: cargo-audit
          path: ~/.cargo/bin/cargo-audit  

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Кэш cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Загрузка target
        uses: actions/download-artifact@v4
        with:
          name: target-artifact
          path: target

      - name: Проверка lint (clippy)
        run: cargo clippy -- -D warnings

  audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Кэш cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Загрузка target
        uses: actions/download-artifact@v4
        with:
          name: target-artifact
          path: target

      - name: Загрузка cargo-audit
        uses: actions/download-artifact@v4
        with:
          name: cargo-audit
          path: ~/.cargo/bin

      - name: Делаем cargo-audit исполняемым
        run: chmod +x ~/.cargo/bin/cargo-audit

      - name: Аудит зависимостей
        run: cargo audit || true

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pitza_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Кэш cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Загрузка target
        uses: actions/download-artifact@v4
        with:
          name: target-artifact
          path: target

      - name: Загрузка diesel_cli
        uses: actions/download-artifact@v4
        with:
          name: diesel-cli
          path: ~/.cargo/bin

      - name: Делаем diesel_cli исполняемым
        run: chmod +x ~/.cargo/bin/diesel

      

      - name: Применение миграций
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/pitza_test
        run: diesel migration run

      - name: Тестирование
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/pitza_test
        run: cargo test --all

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Установка Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Кэш cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Установка tarpaulin и запуск покрытия
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.26.1'
          args: "--out Xml"
        continue-on-error: true

      - name: Загрузка отчета о покрытии в Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./tarpaulin-report.xml

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Логин в DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Сборка и публикация Docker-образа
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pitza-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pitza-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Деплой на сервер
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # логин в Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            # подгрузка последнего образа
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pitza-backend:latest
            # Удаление старых контейнеров
            docker image prune -f
            # запуск контейнеров
            docker-compose -f /home/ubuntu/docker-compose.yml up -d --remove-orphans
